version: '3.1'

services:
  nodejs:
    build:
      context: ./
      dockerfile: Node/Dockerfile
    depends_on:
      - postgres
      - redis
    container_name: nodeapi
    hostname: nodeapi
    environment:
      - NODE_ENV=development
      - API_PORT=8080
      - DB_HOST=postgres  
      - DB_PORT=5432      
      - DB_NAME=database
      - DB_USER=admin
      - DB_PASSWORD=admin
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    restart: unless-stopped
    networks:
      - subnt-database
      - subnt-nodejs

  postgres:
    image: postgres:alpine
    depends_on:
      - redis
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
      PGDATA: /tmp
    restart: unless-stopped
    volumes:
      - ./postgres-persistant-data:/data/postgres
    networks:
      - subnt-database

  redis:
    image: redis:alpine3.11
    container_name: redis
    restart: unless-stopped
    networks:
      - subnt-database

networks:
  subnt-database:
  subnt-nodejs:
