version: 2.1
executors:
  mypublisher:
    environment:
      PROJECT_NAME: tp2-team-6
      USER: "bambin401"
      PASS: "TLrcEFiNckqS8tKCe8KJ3n"
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images (docker-compose)
          command: docker-compose -f ./docker-compose.yaml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: View docker images
          command: docker images -a
      - run:
          name: Save nodejs Docker image
          command: docker save -o ./${PROJECT_NAME}_nodejs.tar project_nodejs
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
  upload-latest:
    executor: mypublisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load saved nodejs image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nodejs.tar
      - run:
          name: View docker images
          command: docker images -a
      - run:
          name: Rename nodejs image
          command: docker tag project_nodejs bambin401/${PROJECT_NAME}_nodejs:latest
      - run:
          name: Publish Node Image to Docker Hub
          command: |
            echo $PASS | base64 --decode | docker login -u $USER --password-stdin
            docker push bambin401/${PROJECT_NAME}_nodejs:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - upload-latest:
          requires:
            - build
          filters:
            branches:
              only: master
